# Generated by Django 3.0.8 on 2020-08-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntiar', '0002_auto_20200813_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volentiar',
            old_name='username',
            new_name='user_name',
        ),
    ]
