# Generated by Django 3.0.8 on 2020-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_doner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner_post',
            name='date',
            field=models.DateField(),
        ),
    ]
