# Generated by Django 3.0.8 on 2020-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_doner', '0002_auto_20200811_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner_post',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
