# Generated by Django 3.0.8 on 2020-08-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_doner', '0005_auto_20200812_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='doner_post',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
