# Generated by Django 3.0.8 on 2020-08-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_doner', '0006_auto_20200813_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
